FROM wangso/imgproc-server:latest
MAINTAINER Songjie Wang "wangso@missouri.edu"
COPY ../NextServer.txt /ImageProcessingWebServices/
WORKDIR /ImageProcessingWebServices/Server
ENTRYPOINT ["python", "server.py"]
