FROM wangso/imgproc-client:latest
MAINTAINER Songjie Wang "wangso@missouri.edu"
COPY ../NextServer.txt /ImageProcessingWebServices/
WORKDIR /ImageProcessingWebServices/Client
ENTRYPOINT ["python", "client.py"]
