apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: imageProcessing
    tier: server
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30067
