apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing
  labels: 
    app: imageProcessing
    tier: server
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: imageProcessing
      tier: server
  template:
    metadata:
      labels:
        app: imageProcessing
        tier: server
    spec:
      nodeSelector:
        nodePool: master
      containers:
      - name: imgproc-server
        image: wangso/imgproc-server:V1
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            hostPort: 5000
        volumeMounts:
          - name: output
            mountPath: /ImageProcessingWebServices/output/server
      hostNetwork: true 
#      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      volumes: 
        - name: output
          hostPath:
            path: /output/server
