apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: traffic-light-instance-01
  labels:
    description: Light
    model: traffic-light
spec:
  deviceModelRef:
    name: traffic-light
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - raspberrypi # give your edge node name
status:
  twins:
    - desired:
        metadata:
          type: string
        value: "OFF"
      propertyName: red
      reported:
        metadata:
          timestamp: "1576146376369"
          type: string
        value: "OFF"
    - desired:
        metadata:
          type: string
        value: "OFF"
      propertyName: yellow
      reported:
        metadata:
          timestamp: "1576146376370"
          type: string
        value: "OFF"
    - desired:
        metadata:
          type: string
        value: "OFF"
      propertyName: green
      reported:
        metadata:
          timestamp: "1576146376369"
          type: string
        value: "OFF"
